export const enum KEYS {
  C = 'C',
  X = 'X',
  Z = 'Z',
  Y = 'Y',
  A = 'A',
  G = 'G',
  L = 'L',
  F = 'F',
  D = 'D',
  B = 'B',
  P = 'P',
  O = 'O',
  R = 'R',
  T = 'T',
  MINUS = '-',
  EQUAL = '=',
  DIGIT_0 = '0',
  DELETE = 'DELETE',
  UP = 'ARROWUP',
  DOWN = 'ARROWDOWN',
  LEFT = 'ARROWLEFT',
  RIGHT = 'ARROWRIGHT',
  ENTER = 'ENTER',
  SPACE = ' ',
  TAB = 'TAB',
  BACKSPACE = 'BACKSPACE',
  ESC = 'ESCAPE',
  PAGEUP = 'PAGEUP',
  PAGEDOWN = 'PAGEDOWN',
  F5 = 'F5',
}

interface HotkeyItem {
  type: string
  children: {
    label: string
    value?: string
  }[]
}

export const HOTKEY_DOC: HotkeyItem[] = [
  {
    type: 'Общие',
    children: [
      { label: 'Вырезать', value: 'Ctrl + X' },
      { label: 'Копировать', value: 'Ctrl + C' },
      { label: 'Вставить', value: 'Ctrl + V' },
      { label: 'Вставить как обычный текст', value: 'Ctrl + Shift + V' },
      { label: 'Быстрое копирование и вставка', value: 'Ctrl + D' },
      { label: 'Выбрать все', value: 'Ctrl + A' },
      { label: 'Отменить', value: 'Ctrl + Z' },
      { label: 'восстановление', value: 'Ctrl + Y' },
      { label: 'Удалить', value: 'Delete / Backspace' },
      { label: 'Множественный выбор', value: 'Нажмите и удерживайте Ctrl или Shift.' },
      { label: 'Открыть поиск и заменить', value: 'Ctrl + F' },
      { label: 'Распечатать', value: 'Ctrl + P' },
      { label: 'Закройте всплывающее окно.', value: 'ESC' },
    ],
  },
  {
    type: 'Показ слайдов',
    children: [
      { label: 'Показ с начала', value: 'F5' },
      { label: 'Показ с текущего слайда', value: 'Shift + F5' },
      { label: 'Предыдущий слайд', value: '↑ / ← / PgUp' },
      { label: 'Следующий слайд', value: '↓ / → / PgDown' },
      { label: 'Следующий слайд', value: 'Enter / Space' },
      { label: 'Выйти из показа', value: 'ESC' },
    ],
  },
  {
    type: 'Редактирование слайдов',
    children: [
      { label: 'Новый слайд', value: 'Enter' },
      { label: 'мобильный холст', value: 'Space + перетаскивание мышью' },
      { label: 'Масштаб холста', value: 'Ctrl + колесо мыши' },
      { label: 'Увеличить холст', value: 'Ctrl + =' },
      { label: 'Уменьшить холст', value: 'Ctrl + -' },
      { label: 'Вписать холст в экран', value: 'Ctrl + 0' },
      { label: 'Предыдущий слайд (если ничего не выбрано)', value: '↑' },
      { label: 'Следующий слайд (если ничего не выбрано)', value: '↓' },
      { label: 'Предыдущая страница', value: 'прокрутка мыши вверх / PgUp' },
      { label: 'Следующая страница', value: 'прокрутка мыши вниз / PgDown' },
      { label: 'Быстрое создание текста', value: 'Дважды щелкните пустое место / T.' },
      { label: 'Быстрое создание прямоугольника', value: 'R' },
      { label: 'Быстро создать круг', value: 'O' },
      { label: 'Быстрое создание строк', value: 'L' },
      { label: 'Выход из состояния чертежа', value: 'правая кнопка мыши' },
    ],
  },
  {
    type: 'Операции с элементами',
    children: [
      { label: 'Перемещение', value: '↑ / ← / ↓ / →' },
      { label: 'Заблокировать', value: 'Ctrl + L' },
      { label: 'Группа', value: 'Ctrl + G' },
      { label: 'Разгруппировать', value: 'Ctrl + Shift + G' },
      { label: 'Верхний уровень', value: 'Alt + F' },
      { label: 'на нижнем этаже', value: 'Alt + B' },
      { label: 'Блокировка соотношения сторон', value: 'Нажмите и удерживайте Ctrl или Shift.' },
      { label: 'Быстрая копия', value: 'Нажмите и удерживайте Ctrl + перетащите' },
      { label: 'Создание горизонтальных/вертикальных линий.', value: 'Нажмите и удерживайте Ctrl или Shift.' },
      { label: 'Элемент переключения фокуса', value: 'Tab' },
      { label: 'Подтвердите обрезку изображения', value: 'Enter' },
      { label: 'Завершает чертеж произвольной формы.', value: 'Enter' },
    ],
  },
  {
    type: 'Редактирование таблицы',
    children: [
      { label: 'Фокус на следующей ячейке.', value: 'Tab' },
      { label: 'Переместить фокус ячейки', value: '↑ / ← / ↓ / →' },
      { label: 'Вставить строку выше', value: 'Ctrl + ↑' },
      { label: 'Вставьте строку ниже', value: 'Ctrl + ↓' },
      { label: 'Вставить столбец слева', value: 'Ctrl + ←' },
      { label: 'Вставьте столбец справа', value: 'Ctrl + →' },
    ],
  },
  {
    type: 'Редактирование данных диаграммы',
    children: [
      { label: 'Переход на следующую строку.', value: 'Enter' },
    ],
  },
  {
    type: 'Редактирование текста',
    children: [
      { label: 'Полужирный', value: 'Ctrl + B' },
      { label: 'Курсив', value: 'Ctrl + I' },
      { label: 'Подчёркивание', value: 'Ctrl + U' },
      { label: 'Встроенный код', value: 'Ctrl + E' },
      { label: 'Надстрочный', value: 'Ctrl + ;' },
      { label: 'Подстрочный', value: `Ctrl + '` },
      { label: 'Выбрать абзац', value: `ESC` },
    ],
  },
  {
    type: 'Другие горячие клавиши',
    children: [
      { label: 'Добавить изображение — вставка изображения из системного буфера обмена.' },
      { label: 'Добавить изображения — перетащите локальные изображения на холст.' },
      { label: 'Добавить изображение – Вставить код SVG на холст' },
      { label: 'Добавить изображение — вставить ссылку на изображение из пикселей.' },
      { label: 'Добавить текст — вставить текст из системного буфера обмена.' },
      { label: 'Добавить текст — перетащить внешний выделенный текст на холст.' },
      { label: 'Редактирование текста — поддерживает синтаксис markdown для создания списков и ссылок.' },
    ],
  },
]